import Head from "next/head";
import Image from "next/image";
import SideBar from "../components/sidebar/SideBar";
import Dashboard from "../components/dashboard/Dashboard";
// import TransactionIn from "../components/transaction/TransactionIn";

const style = {
  container: `flex flex-row justify-between w-screen`,
};

export default function Home() {
  return (
    <div className={style.container}>
      <Head>
        <title>Convexity Bantu Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SideBar />
      <Dashboard />
    </div>
  );
}
