import Head from "next/head";
import React, { useState, useEffect } from "react";
import SideBar from "../components/sidebar/SideBar";
import Dashboard from "../components/dashboard/Dashboard";
import AddWalletForm from "../components/form/AddWalletForm";
import AddWalletBtn from "../components/form/AddWalletBtn";
import { Toaster } from "react-hot-toast";

const style = {
  container: `relative flex flex-row justify-end w-screen`,
};

export default function Home() {

	// State for Add Wallet Modal
	const [openModal, setOpenModal] = useState(false);
	// State for Add Wallet Button
	const [hideAddWalletBtn, setHideAddWalletBtn] = useState(false);


	// Function to handle Modal control
	const toggleModal = () => {
		setOpenModal(!openModal);
	};

  return (
    <div className={style.container}>
      <Head>
        <title>Convexity Bantu Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SideBar />
      <Dashboard />
      <AddWalletForm openModal={openModal} toggleModal={toggleModal} />
      <AddWalletBtn
        toggleModal={toggleModal}
        hideAddWalletBtn={hideAddWalletBtn}
      />
      <Toaster />
    </div>
  );
}
