import Head from "next/head";
import React, { useState, useEffect } from "react";
import Header from "../components/dashboard/Header";
import AddWalletBtn from "../components/form/AddWalletBtn";
import AddWalletForm from "../components/form/AddWalletForm";

const style = {
  container: `relative h-[100vh] w-[100vw] flex flex-col`,
};

export default function Home() {

  return (
    <div className={style.container}>
      <Head>
        <title>Convexity Bantu Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header/>
    </div>
  );
}
