import Head from "next/head";
import React, { useState, useEffect } from "react";
import ExchangeCard from "../components/dashboard/ExchangeCard";
import Header from "../components/dashboard/Header";

const style = {
  container: `relative h-[100vh] w-[100vw] flex flex-col`,
};

export default function Home() {

  return (
    <div className={style.container}>
      <Head>
        <title>Convexity Bantu Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header/>
      <ExchangeCard />
    </div>
  );
}
