import Head from "next/head";
import React, { useState, useEffect } from "react";
import HomePageLayout from "../components/HomePageLayout";

export default function Home() {

  return (
    <HomePageLayout>
      <Head>
        <title>Convexity Bantu Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </HomePageLayout>
  );
}
